import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const recipes = [
    {
        title: "Pizza",
        thumbnail: "https://cloud.mysteryscience.com/image/fetch/f_auto,q_auto/https://www.dropbox.com/s/tchd8wbvqy5h7of/083-Pizza-Thumbnail-Site.png%3Fdl%3D1",
        tools: ["Oven", "Pizza Cutter", "Pizza Pan"],
        ingredients: ["Dough", "Tomatoes", "Cheese"],
        description: "A pizza is a flat, round, deep-dish, thin-crust pizza.",
    },
    {
        title: "Pizza",
        thumbnail: "https://cloud.mysteryscience.com/image/fetch/f_auto,q_auto/https://www.dropbox.com/s/tchd8wbvqy5h7of/083-Pizza-Thumbnail-Site.png%3Fdl%3D1",
        tools: ["Oven", "Pizza Cutter", "Pizza Pan"],
        ingredients: ["Dough", "Tomatoes", "Cheese"],
        description: "A pizza is a flat, round, deep-dish, thin-crust pizza.",
    },
    {
        title: "Pizza",
        thumbnail: "https://cloud.mysteryscience.com/image/fetch/f_auto,q_auto/https://www.dropbox.com/s/tchd8wbvqy5h7of/083-Pizza-Thumbnail-Site.png%3Fdl%3D1",
        tools: ["Oven", "Pizza Cutter", "Pizza Pan"],
        ingredients: ["Dough", "Tomatoes", "Cheese"],
        description: "A pizza is a flat, round, deep-dish, thin-crust pizza.",
    },
    {
        title: "Pizza",
        thumbnail: "https://cloud.mysteryscience.com/image/fetch/f_auto,q_auto/https://www.dropbox.com/s/tchd8wbvqy5h7of/083-Pizza-Thumbnail-Site.png%3Fdl%3D1",
        tools: ["Oven", "Pizza Cutter", "Pizza Pan"],
        ingredients: ["Dough", "Tomatoes", "Cheese"],
        description: "A pizza is a flat, round, deep-dish, thin-crust pizza.",
    },
  ];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="w-full h-full flex flex-row">
            <div className="min-w-[600px] max-w-[700px] w-1/3 h-full bg-primary px-12 py-8 flex flex-col">
                <h2 className="text-white text-4xl mb-8 text-center">My Kitchen</h2>
                <div className="w-full h-96 grid grid-rows-1 grid-cols-2 px-4 flex-1">
                    <div className="min-h-10 px-8 flex flex-col">
                        <h3 className="text-white text-2xl pb-4 pt-2 text-center">Tools</h3>
                        <input type="text" className="w-full text-center text-xl py-1 bg-black/60 text-white" placeholder="Add Tool" />
                        <ul className="bg-secondary grow">

                        </ul>
                    </div>
                    <div className="min-h-10 px-8 flex flex-col">
                        <h3 className="text-white text-2xl pb-4 pt-2 text-center">Ingredients</h3>
                        <input type="text" className="w-full text-center text-xl py-1 bg-black/60 text-white" placeholder="Add Ingredient" />
                        <ul className="bg-secondary grow">

                        </ul>
                    </div>
                </div>
                <h3 className="text-white text-3xl mt-8 mb-4 text-center">Favorites</h3>
                <ul className="bg-secondary grow">

                </ul>
            </div>
            <div className="grow h-full py-8 bg-background">
                <h1 className="text-center text-5xl font-semibold mb-8 text-darkText">Recipes by Ingredients</h1>
                    <div className="text-2xl text-center mb-6 text-darkText"><a className="underline text-blue-600">Login</a> or <a className="underline text-blue-600">Sign up</a> to submit a recipe!</div>
                <ul className="w-full px-20">
                    {recipes.map((recipe, recipeIndex) => (
                        <li key={recipe.title} className={`flex flex-row bg-primary text-white ${/*recipeIndex < recipes.length - 1 ? 'border-b-2 border-blue-400' : ''*/''} my-4`}>
                            <div className="h-40 w-40 p-3 shrink-0">
                                <img src={recipe.thumbnail} alt={recipe.title} className="h-full w-full" />
                            </div>
                            <div className="grow flex flex-row py-4 px-8">
                                <div className="flex-1">
                                    <h2 className="text-2xl font-semibold">{recipe.title}</h2>
                                    <p className="text-xl">{recipe.description}</p>
                                </div>
                                    <div className="flex-1 px-8">
                                        <h3 className="text-center font-semibold text-xl">Tools</h3>
                                            {recipe.tools.map((tool, toolIndex) => (
                                                <span className="text-xl" key={tool}> {tool}{toolIndex < recipe.tools.length - 1 ? ", " : '.'}</span>
                                            ))}
                                    </div>
                                    <div className="flex-1 px-8">
                                        <h3 className="text-center font-semibold text-xl">Ingredients</h3>
                                            {recipe.ingredients.map((ingredient, ingredientIndex) => (
                                                <span className="text-xl" key={ingredient}> {ingredient}{ingredientIndex < recipe.ingredients.length - 1 ? ", " : '.'}</span>
                                            ))}
                                    </div>
                            </div>
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    </>
  );
};

export default Home;